{spec, codec_last,
 #spec{name = <<"query">>,
       xmlns = <<"jabber:iq:last">>,
       result = {last, '$seconds', '$text'},
       attrs = [#attr{name = <<"seconds">>,
                      default = undefined,
                      dec = {integer, 0, unlimited}}],
       cdata = #cdata{label = '$text'}}}.
{spec, codec_version,
 #spec{name = <<"query">>,
       xmlns = <<"jabber:iq:version">>,
       result = {version, '$name', '$version', '$os'},
       els = [#spec{name = <<"name">>,
                    min = 1,
                    max = 1,
                    result = '$cdata',
                    cdata = #cdata{label = '$cdata', required = true}},
              #spec{name = <<"version">>,
                    min = 1,
                    max = 1,
                    result = '$cdata',
                    cdata = #cdata{label = '$cdata', required = true}},
              #spec{name = <<"os">>,
                    max = 1,
                    result = '$cdata',
                    cdata = #cdata{label = '$cdata', required = true}}]}}.
{spec, codec_roster,
 #spec{name = <<"query">>,
       xmlns = <<"jabber:iq:roster">>,
       result = '$item',
       els = [#spec{name = <<"item">>,
                    result = {roster, '$jid', '$name',
                              '$groups', '$subscription', '$ask'},
                    attrs = [#attr{name = <<"jid">>,
                                   required = true,
                                   dec = jid},
                             #attr{name = <<"name">>},
                             #attr{name = <<"subscription">>,
                                   default = none,
                                   dec = {enum, [none,to,from,both,remove]}},
                             #attr{name = <<"ask">>,
                                   default = undefined,
                                   dec = {enum, [subscribe]}}],
                    els = [#spec{name = <<"group">>,
                                 label = '$groups',
                                 result = '$cdata',
                                 cdata = #cdata{required = true,
                                                label = '$cdata'}}]}]}}.
{spec, codec_disco_info,
 #spec{name = <<"query">>,
       xmlns = <<"http://jabber.org/protocol/disco#info">>,
       result = {disco_info, '$identity', '$feature'},
       els = [#spec{name = <<"identity">>,
                    result = {'$category', '$type', '$name'},
                    attrs = [#attr{name = <<"category">>,
                                   required = true},
                             #attr{name = <<"type">>,
                                   required = true},
                             #attr{name = <<"name">>}]},
              #spec{name = <<"feature">>,
                    result = '$var',
                    attrs = [#attr{name = <<"var">>,
                                   required = true}]}]}}.
{spec, codec_disco_items,
 #spec{name = <<"query">>,
       xmlns = <<"http://jabber.org/protocol/disco#items">>,
       result = {disco_items, '$node', '$item'},
       attrs = [#attr{name = <<"node">>}],
       els = [#spec{name = <<"item">>,
                    result = {'$jid', '$name', '$node'},
                    attrs = [#attr{name = <<"jid">>,
                                   required = true,
                                   dec = jid},
                             #attr{name = <<"name">>},
                             #attr{name = <<"node">>}]}]}}.
{spec, codec_iq,
 #spec{name = <<"iq">>,
       result = {iq, '$id', '$type', '$lang'},
       attrs = [#attr{name = <<"id">>,
                      required = true},
                #attr{name = <<"type">>,
                      required = true,
                      dec = {enum, [get, set, result, error]}},
                #attr{name = <<"xml:lang">>,
                      label = '$lang'}]}}.

%% Local Variables:
%% mode: erlang
%% End:
%% vim: set filetype=erlang tabstop=8:
